services:
  - type: web
    name: deepface-emotion-api
    env: python
    plan: free
    buildCommand: conda env update -f environment.yml
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      -